### ISSUE TITLE
npm create-react-app .

### ISSUE THREAD

**Issue by AIPO** [uiacademy/homework#2]
`npm create-react-app .` neveikia nuforkinus repositoriją, nes jau yra direktorijos. Variantas naudoti CDN yra tinkamas?
Koks geriausias būdas sujungti `create-react-app` su šia repo?

**Comment by budaman** [comment]
Sveikas @AIPO. Siūlom generuoti folderį kaip pvz `create-react-app client` ir `client` folderyje atlikti užduotį. Taip pat nėra griežtai draudžiama susikurti savo repozitorija ir atsiųsti galutinį variantą joje jei yra noro.
