### ISSUE TITLE
Dropdown elementas

### ISSUE THREAD

**Issue by CMantvis** [uiacademy/homework#4]
Sveiki, ką turėtų rodyti dropdown elemento atskyrimas tuo brūkšniu ir kodėl dropdownas užstoja inputą, taip pat prie pirmo elemento yra icona ar ji rodo jog elementas pasirinktas ar ten hover efektas?

**Comment by uiacademy** [comment]
Sveiki, 

1.  Paspaudus ant pirmame screenshot'e ant esancio input elemento, turi atsirasti dropdown (kuris hoverina inputa). I
2. Antrame screenshot Kur matosi  pirmas zodis "Game"   - tai jau yra vartotojo input'as
3. Bruksnys atskiria inputa nuo to kas gryzta is API.
4. Icona tiesiog matosi shalia input ant hover.

Dizainas kazkiek atitinka KAYAK naudojamus Autocomplete elementus.
https://www.kayak.com/cars
