### ISSUE TITLE
Reikalingas patikslinimas dėl paieškos laukelio dizaino

### ISSUE THREAD

**Issue by lukaskairys** [uiacademy/homework#9]
Darant užduotį iškilo klausimų dėl "input field". Žiūrint į jūsų pateiktus dizaino pavyzdžius (žr. žemiau), darau prielaidą, jog "input field" stilius keičiasi atsiradus autocomplete sąrašaui po apačia. 
Man atrodo, kad tai neigiamai veikia UX. Teksto įvedimo laukelis persikelia į aukštesnę poziciją, taip pat pasislenka į dešinę atsiradus padublikuotai filmų ikonai. Nemanau, kad vedant tekstą malonu kai paieškos laukelis šokinėja į kitą vietą. Taip pat pagal pavyzdį užsidengia paieškso mygtukas, kas nebeleidžia vartotojui ieškot pagal savo raktinį žodį, o verčia pasirinkti kažką iš sąrašo. Manau, kad paieškos laukelio stiliaus ir jame esančių elementų geriau nekeisti. 

Jei vis dėl to turi būti taip kaip pavyzdyje, tai naujas paieškos lauko stilius turi būti pritaikytas atsiradus autocomplete sąrašui (t.y. įvedus trečią simbolį) ar jau įvedus pirmą simbolį.

![image](https://user-images.githubusercontent.com/65352499/110252291-5a7a1a80-7f8d-11eb-85fd-1070ae7fa31d.png)

**Comment by uiacademy** [comment]
Sveiki, 
Sutinku dėl UX. ir pastabos tikrai geros. Tiesa sakant forma yra išimta iš context, 
https://www.kayak.com/cars
Mes norėjome patikrinti css žinias, dėl to palikome tokią animaciją.
Tai trumpai atsakant, pabandykyte/padarykite taip, kaip mock'e, galit padaryti, kad neuždengtų button, kad input vieta nepašoktų, bet kad tas hoveris gautųsi
O input field stilius keičiasi tik paspaudus ant input - dar nieko neįvedus.

Šarūnas
